In [1]:
import sklearn
import pandas
import numpy
import sys

In [2]:
import pandas as pd
import numpy as np


In [3]:
url='https://archive.ics.uci.edu/ml/machine-learning-databases/molecular-biology/promoter-gene-sequences/promoters.data'


In [4]:
names=['Class','id','Sequence']
data=pd.read_csv(url,names=names)


In [5]:
data.head()

Class         id                                           Sequence
0     +        S10  \t\ttactagcaatacgcttgcgttcggtggttaagtatgtataat...
1     +       AMPC  \t\ttgctatcctgacagttgtcacgctgattggtgtcgttacaat...
2     +       AROH  \t\tgtactagagaactagtgcattagcttatttttttgttatcat...
3     +      DEOP2  \taattgtgatgtgtatcgaagtgtgttgcggagtagatgttagaa...
4     +  LEU1_TRNA  \ttcgataattaactattgacgaaaagctgaaaaccactagaatgc...

In [6]:
print(data.iloc[0])

Class                                                       +
id                                                        S10
Sequence    \t\ttactagcaatacgcttgcgttcggtggttaagtatgtataat...
Name: 0, dtype: object


In [7]:
print(data.iloc[:5])

  Class         id                                           Sequence
0     +        S10  \t\ttactagcaatacgcttgcgttcggtggttaagtatgtataat...
1     +       AMPC  \t\ttgctatcctgacagttgtcacgctgattggtgtcgttacaat...
2     +       AROH  \t\tgtactagagaactagtgcattagcttatttttttgttatcat...
3     +      DEOP2  \taattgtgatgtgtatcgaagtgtgttgcggagtagatgttagaa...
4     +  LEU1_TRNA  \ttcgataattaactattgacgaaaagctgaaaaccactagaatgc...


In [8]:
url

'https://archive.ics.uci.edu/ml/machine-learning-databases/molecular-biology/promoter-gene-sequences/promoters.data'

In [9]:
print(url)

https://archive.ics.uci.edu/ml/machine-learning-databases/molecular-biology/promoter-gene-sequences/promoters.data


In [10]:
classes=data.loc[:,'Class']
print(classes[:5])

0    +
1    +
2    +
3    +
4    +
Name: Class, dtype: object


In [11]:
sequences=list(data.loc[:,'Sequence'])
dataset={}
for i,seq in enumerate(sequences):
    nucleotides=list(seq)
    nucleotides=[x for x in nucleotides if x!='\t']
    nucleotides.append(classes[i])
    dataset[i]=nucleotides
print(dataset[3])
    


['a', 'a', 't', 't', 'g', 't', 'g', 'a', 't', 'g', 't', 'g', 't', 'a', 't', 'c', 'g', 'a', 'a', 'g', 't', 'g', 't', 'g', 't', 't', 'g', 'c', 'g', 'g', 'a', 'g', 't', 'a', 'g', 'a', 't', 'g', 't', 't', 'a', 'g', 'a', 'a', 't', 'a', 'c', 't', 'a', 'a', 'c', 'a', 'a', 'a', 'c', 't', 'c', '+']


dframe=pd.Dataframe(dataset)
print(dframe)

In [12]:
dframe=pd.DataFrame(dataset) 
print(dframe)

   0   1   2   3   4   5   6   7   8   9    ... 96  97  98  99  100 101 102  \
0    t   t   g   a   t   a   c   t   c   t  ...   c   c   t   a   g   c   g   
1    a   g   t   a   c   g   a   t   g   t  ...   c   g   a   g   a   c   t   
2    c   c   a   t   g   g   g   t   a   t  ...   g   c   t   a   g   t   a   
3    t   t   c   t   a   g   g   c   c   t  ...   a   t   g   g   a   c   t   
4    a   a   t   g   t   g   g   t   t   a  ...   g   a   a   g   g   a   t   
5    g   t   a   t   a   c   g   a   t   a  ...   t   g   c   g   c   a   c   
6    c   c   g   g   a   a   g   c   a   a  ...   a   g   c   t   a   t   t   
7    a   c   a   a   t   a   t   a   a   t  ...   g   a   g   g   t   g   c   
8    a   t   g   t   t   g   g   a   t   t  ...   a   c   a   t   g   g   a   
9    t   g   a   g   a   g   g   a   a   t  ...   c   t   a   a   t   c   a   
10   a   a   a   t   a   a   a   a   t   c  ...   c   t   c   c   c   c   c   
11   c   c   c   g   c   g   g   c   a   c  ...   c 

In [13]:
df=dframe.transpose()
print(df)

    0  1  2  3  4  5  6  7  8  9   ... 48 49 50 51 52 53 54 55 56 57
0    t  a  c  t  a  g  c  a  a  t  ...  g  c  t  t  g  t  c  g  t  +
1    t  g  c  t  a  t  c  c  t  g  ...  c  a  t  c  g  c  c  a  a  +
2    g  t  a  c  t  a  g  a  g  a  ...  c  a  c  c  c  g  g  c  g  +
3    a  a  t  t  g  t  g  a  t  g  ...  a  a  c  a  a  a  c  t  c  +
4    t  c  g  a  t  a  a  t  t  a  ...  c  c  g  t  g  g  t  a  g  +
..  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
101  c  c  t  c  a  a  t  g  g  c  ...  g  a  a  c  t  a  t  a  t  -
102  g  t  a  t  t  c  t  c  a  a  ...  t  c  a  a  c  a  t  t  g  -
103  c  g  c  g  a  c  t  a  c  g  ...  a  a  g  g  c  t  t  c  c  -
104  c  t  c  g  t  c  c  t  c  a  ...  a  g  g  a  g  g  a  a  c  -
105  t  a  a  c  a  t  t  a  a  t  ...  t  c  a  a  g  a  a  c  t  -

[106 rows x 58 columns]


In [14]:
df.rename(columns={57:'Class'},inplace=True)
print(df)

     0  1  2  3  4  5  6  7  8  9  ... 48 49 50 51 52 53 54 55 56 Class
0    t  a  c  t  a  g  c  a  a  t  ...  g  c  t  t  g  t  c  g  t     +
1    t  g  c  t  a  t  c  c  t  g  ...  c  a  t  c  g  c  c  a  a     +
2    g  t  a  c  t  a  g  a  g  a  ...  c  a  c  c  c  g  g  c  g     +
3    a  a  t  t  g  t  g  a  t  g  ...  a  a  c  a  a  a  c  t  c     +
4    t  c  g  a  t  a  a  t  t  a  ...  c  c  g  t  g  g  t  a  g     +
..  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. ..   ...
101  c  c  t  c  a  a  t  g  g  c  ...  g  a  a  c  t  a  t  a  t     -
102  g  t  a  t  t  c  t  c  a  a  ...  t  c  a  a  c  a  t  t  g     -
103  c  g  c  g  a  c  t  a  c  g  ...  a  a  g  g  c  t  t  c  c     -
104  c  t  c  g  t  c  c  t  c  a  ...  a  g  g  a  g  g  a  a  c     -
105  t  a  a  c  a  t  t  a  a  t  ...  t  c  a  a  g  a  a  c  t     -

[106 rows x 58 columns]


In [15]:
series=[]
for name in df.columns:
    series.append(df[name].value_counts())
    

In [16]:
series

[t    38
 c    27
 a    26
 g    15
 Name: 0, dtype: int64, a    34
 t    26
 g    24
 c    22
 Name: 1, dtype: int64, a    30
 g    28
 t    27
 c    21
 Name: 2, dtype: int64, c    30
 g    28
 t    26
 a    22
 Name: 3, dtype: int64, a    36
 g    29
 t    22
 c    19
 Name: 4, dtype: int64, a    42
 t    24
 g    22
 c    18
 Name: 5, dtype: int64, a    38
 t    30
 c    21
 g    17
 Name: 6, dtype: int64, a    34
 t    32
 g    20
 c    20
 Name: 7, dtype: int64, a    33
 t    32
 c    22
 g    19
 Name: 8, dtype: int64, a    36
 t    28
 c    22
 g    20
 Name: 9, dtype: int64, a    38
 t    31
 c    22
 g    15
 Name: 10, dtype: int64, c    31
 t    29
 g    25
 a    21
 Name: 11, dtype: int64, t    34
 a    29
 g    29
 c    14
 Name: 12, dtype: int64, c    38
 a    24
 g    23
 t    21
 Name: 13, dtype: int64, t    54
 a    23
 g    16
 c    13
 Name: 14, dtype: int64, t    54
 c    24
 a    17
 g    11
 Name: 15, dtype: int64, g    53
 t    24
 a    15
 c    14
 Name: 16, dty

In [17]:
info=pd.DataFrame(series)
details=info.transpose()
print(info)


          t     c     a     g     -     +
0      38.0  27.0  26.0  15.0   NaN   NaN
1      26.0  22.0  34.0  24.0   NaN   NaN
2      27.0  21.0  30.0  28.0   NaN   NaN
3      26.0  30.0  22.0  28.0   NaN   NaN
4      22.0  19.0  36.0  29.0   NaN   NaN
5      24.0  18.0  42.0  22.0   NaN   NaN
6      30.0  21.0  38.0  17.0   NaN   NaN
7      32.0  20.0  34.0  20.0   NaN   NaN
8      32.0  22.0  33.0  19.0   NaN   NaN
9      28.0  22.0  36.0  20.0   NaN   NaN
10     31.0  22.0  38.0  15.0   NaN   NaN
11     29.0  31.0  21.0  25.0   NaN   NaN
12     34.0  14.0  29.0  29.0   NaN   NaN
13     21.0  38.0  24.0  23.0   NaN   NaN
14     54.0  13.0  23.0  16.0   NaN   NaN
15     54.0  24.0  17.0  11.0   NaN   NaN
16     24.0  14.0  15.0  53.0   NaN   NaN
17     18.0  29.0  40.0  19.0   NaN   NaN
18     23.0  44.0  27.0  12.0   NaN   NaN
19     24.0  24.0  31.0  27.0   NaN   NaN
20     34.0  22.0  28.0  22.0   NaN   NaN
21     26.0  20.0  31.0  29.0   NaN   NaN
22     27.0  27.0  22.0  30.0   Na

In [18]:
print(details)

      0     1     2     3     4     5     6     7     8     9  ...    48  \
t  38.0  26.0  27.0  26.0  22.0  24.0  30.0  32.0  32.0  28.0  ...  21.0   
c  27.0  22.0  21.0  30.0  19.0  18.0  21.0  20.0  22.0  22.0  ...  36.0   
a  26.0  34.0  30.0  22.0  36.0  42.0  38.0  34.0  33.0  36.0  ...  23.0   
g  15.0  24.0  28.0  28.0  29.0  22.0  17.0  20.0  19.0  20.0  ...  26.0   
-   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   
+   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   

     49    50    51    52    53    54    55    56  Class  
t  22.0  23.0  33.0  35.0  30.0  23.0  29.0  34.0    NaN  
c  42.0  31.0  32.0  21.0  32.0  29.0  29.0  17.0    NaN  
a  24.0  28.0  27.0  25.0  22.0  26.0  24.0  27.0    NaN  
g  18.0  24.0  14.0  25.0  22.0  28.0  24.0  28.0    NaN  
-   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   53.0  
+   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   53.0  

[6 rows x 58 columns]


In [19]:
numerical_df=pd.get_dummies(df)
numerical_df

0_a  0_c  0_g  0_t  1_a  1_c  1_g  1_t  2_a  2_c  ...  55_a  55_c  55_g  \
0      0    0    0    1    1    0    0    0    0    1  ...     0     0     1   
1      0    0    0    1    0    0    1    0    0    1  ...     1     0     0   
2      0    0    1    0    0    0    0    1    1    0  ...     0     1     0   
3      1    0    0    0    1    0    0    0    0    0  ...     0     0     0   
4      0    0    0    1    0    1    0    0    0    0  ...     1     0     0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   
101    0    1    0    0    0    1    0    0    0    0  ...     1     0     0   
102    0    0    1    0    0    0    0    1    1    0  ...     0     0     0   
103    0    1    0    0    0    0    1    0    0    1  ...     0     1     0   
104    0    1    0    0    0    0    0    1    0    1  ...     1     0     0   
105    0    0    0    1    1    0    0    0    1    0  ...     0     1     0   

     55_t  56_a  56_c  56_g  56_t  Class_+  Class_-  
0       0     0     0     0     1        1        0  
1       0     1     0     0     0        1        0  
2       0     0     0     1     0        1        0  
3       1     0     1     0     0        1        0  
4       0     0     0     1     0        1        0  
..    ...   ...   ...   ...   ...      ...      ...  
101     0     0     0     0     1        0        1  
102     1     0     0     1     0        0        1  
103     0     0     1     0     0        0        1  
104     0     0     1     0     0        0        1  
105     0     0     0     0     1        0        1  

[106 rows x 230 columns]

In [20]:
df=numerical_df.drop(columns=['Class_-'])
df.rename(columns={'Class_+':'Class'},inplace=True)
print(df.iloc[:5])


   0_a  0_c  0_g  0_t  1_a  1_c  1_g  1_t  2_a  2_c  ...  54_t  55_a  55_c  \
0    0    0    0    1    1    0    0    0    0    1  ...     0     0     0   
1    0    0    0    1    0    0    1    0    0    1  ...     0     1     0   
2    0    0    1    0    0    0    0    1    1    0  ...     0     0     1   
3    1    0    0    0    1    0    0    0    0    0  ...     0     0     0   
4    0    0    0    1    0    1    0    0    0    0  ...     1     1     0   

   55_g  55_t  56_a  56_c  56_g  56_t  Class  
0     1     0     0     0     0     1      1  
1     0     0     1     0     0     0      1  
2     0     0     0     0     1     0      1  
3     0     1     0     1     0     0      1  
4     0     0     0     0     1     0      1  

[5 rows x 229 columns]


In [21]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import classification_report,accuracy_score
from sklearn import model_selection

In [22]:
X=np.array(df.drop(['Class'],1))
Y=np.array(df['Class'])
X_train,X_test,Y_train,Y_test=model_selection.train_test_split(X,Y,test_size=0.2,random_state=1)

In [23]:
X_test

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [24]:
X_train

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 1]], dtype=uint8)

In [25]:
Y_test

array([0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0],
      dtype=uint8)

In [26]:
scoring='accuracy'
names=["KNearest Neighbors","Gaussian Process","Decision Tree","Random Forest","Neural Net","AdaBoost","Naive Bayes","SVM Linear","SVM RBF","SVM Sigmoid"]
classifiers=[KNeighborsClassifier(n_neighbors=3),
             GaussianProcessClassifier(1.0*RBF(1.0)),
             DecisionTreeClassifier(max_depth=5),
             RandomForestClassifier(max_depth=5,n_estimators=10,max_features=1),
             MLPClassifier(alpha=1),
             AdaBoostClassifier(),
             GaussianNB(),
             SVC(kernel='linear'),
             SVC(kernel='rbf'),
             SVC(kernel='sigmoid')
            ]
models=zip(names,classifiers)
results=[]
names=[]
for name, model in models:
    kfold=model_selection.KFold(n_splits =10,random_state=1)
    cv_results=model_selection.cross_val_score(model,X_train,Y_train,cv=kfold,scoring=scoring)
    results.append(cv_results)
    names.append(name)
    msg="{0}:{1}({2})".format(name,cv_results.mean(),cv_results.std())
    print(msg)

KNearest Neighbors:0.7916666666666667(0.1359409367026906)
Gaussian Process:0.8680555555555556(0.10472074858969059)
Decision Tree:0.7819444444444444(0.14394277197879116)
Random Forest:0.5847222222222223(0.2120456289703518)


C:\New folder\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\New folder\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\New folder\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\New folder\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\New folder\lib\site-packages\

Neural Net:0.8444444444444444(0.097182531580755)
AdaBoost:0.9069444444444444(0.06833841444523636)
Naive Bayes:0.8486111111111111(0.10119845128859373)
SVM Linear:0.8805555555555555(0.07510281019219875)
SVM RBF:0.7763888888888889(0.10233576122104802)
SVM Sigmoid:0.575(0.1868765354617129)


C:\New folder\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\New folder\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\New folder\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\New folder\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change f

In [27]:
for name, model in models:
    model.fit(X_train,Y_train)
    pre=model.predict(X_test)
    print(name)
    print(accuracy_score(Y_test, pre))
    print(classification_report(Y_test, pre))

In [28]:
X_train

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 1]], dtype=uint8)

In [29]:
print(names)

['KNearest Neighbors', 'Gaussian Process', 'Decision Tree', 'Random Forest', 'Neural Net', 'AdaBoost', 'Naive Bayes', 'SVM Linear', 'SVM RBF', 'SVM Sigmoid']


In [30]:
print(models)

In [31]:
Y_train

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1], dtype=uint8)

In [32]:
scoring='accuracy'
models=[]
models.append(('KNearest Neighbors', KNeighborsClassifier(n_neighbors=3)))
models.append(('Gaussian Process',  GaussianProcessClassifier(1.0*RBF(1.0))))
models.append(('Decision Tree' ,   DecisionTreeClassifier(max_depth=5)))
models.append(('Random Forest',     RandomForestClassifier(max_depth=5,n_estimators=10,max_features=1)))
models.append(('Neural Net'       ,    MLPClassifier(alpha=1)))
models.append(('AdaBoost'        , AdaBoostClassifier()))
models.append(('Naive Bayes',  GaussianNB()))
models.append(('SVM Linear', SVC(kernel='linear')))
models.append(('SVM RBF',SVC(kernel='rbf')))
models.append(('SVM RBF' ,    SVC(kernel='sigmoid')))
results=[]
names=[]
for name, model in models:
    kfold=model_selection.KFold(n_splits =10,random_state=1)
    cv_results=model_selection.cross_val_score(model,X_train,Y_train,cv=kfold,scoring=scoring)
    results.append(cv_results)
    names.append(name)
    msg="{0}:{1}({2})".format(name,cv_results.mean(),cv_results.std())
    print(msg)           



KNearest Neighbors:0.7916666666666667(0.1359409367026906)
Gaussian Process:0.8680555555555556(0.10472074858969059)
Decision Tree:0.7819444444444444(0.1350939887725177)
Random Forest:0.5944444444444444(0.11348165675453054)


C:\New folder\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\New folder\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\New folder\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\New folder\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\New folder\lib\site-packages\

Neural Net:0.8930555555555555(0.06662324975117476)
AdaBoost:0.9069444444444444(0.06833841444523636)
Naive Bayes:0.8486111111111111(0.10119845128859373)
SVM Linear:0.8805555555555555(0.07510281019219875)
SVM RBF:0.7763888888888889(0.10233576122104802)
SVM RBF:0.575(0.1868765354617129)


C:\New folder\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\New folder\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\New folder\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\New folder\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change f

In [33]:
for name, model in models:
    model.fit(X_train,Y_train)
    pre=model.predict(X_test)
    print(name)
    print(accuracy_score(Y_test, pre))
    print(classification_report(Y_test, pre))

KNearest Neighbors
0.7727272727272727
              precision    recall  f1-score   support

           0       1.00      0.67      0.80        15
           1       0.58      1.00      0.74         7

    accuracy                           0.77        22
   macro avg       0.79      0.83      0.77        22
weighted avg       0.87      0.77      0.78        22

Gaussian Process
0.9545454545454546
              precision    recall  f1-score   support

           0       1.00      0.93      0.97        15
           1       0.88      1.00      0.93         7

    accuracy                           0.95        22
   macro avg       0.94      0.97      0.95        22
weighted avg       0.96      0.95      0.96        22

Decision Tree
0.8181818181818182
              precision    recall  f1-score   support

           0       0.92      0.80      0.86        15
           1       0.67      0.86      0.75         7

    accuracy                           0.82        22
   macro avg       0.

C:\New folder\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
C:\New folder\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


Neural Net
0.9545454545454546
              precision    recall  f1-score   support

           0       1.00      0.93      0.97        15
           1       0.88      1.00      0.93         7

    accuracy                           0.95        22
   macro avg       0.94      0.97      0.95        22
weighted avg       0.96      0.95      0.96        22

AdaBoost
0.8181818181818182
              precision    recall  f1-score   support

           0       1.00      0.73      0.85        15
           1       0.64      1.00      0.78         7

    accuracy                           0.82        22
   macro avg       0.82      0.87      0.81        22
weighted avg       0.88      0.82      0.82        22

Naive Bayes
0.9090909090909091
              precision    recall  f1-score   support

           0       1.00      0.87      0.93        15
           1       0.78      1.00      0.88         7

    accuracy                           0.91        22
   macro avg       0.89      0.93      

C:\New folder\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
